// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6ygl65A4YFK6qZ_8vqEgttSlgN3aA8A',
    appId: '1:149624228243:web:7d8888372c8bc6c448c066',
    messagingSenderId: '149624228243',
    projectId: 'fafu-869a8',
    authDomain: 'fafu-869a8.firebaseapp.com',
    storageBucket: 'fafu-869a8.firebasestorage.app',
    measurementId: 'G-HGMT9DWMS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1my_OECpsWsCX5n7FFZpC3BpCLNv_nE',
    // Must match the applicationId (com.getfafo.app) — the "Fafo Android"
    // Firebase app registered for the production package name.
    appId: '1:149624228243:android:f9f6a273264a615248c066',
    messagingSenderId: '149624228243',
    projectId: 'fafu-869a8',
    storageBucket: 'fafu-869a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwD4RFWe_MGs6gja0C-aX_skpF7CEkFLc',
    // Must match the iOS bundle id (com.getfafo.app) — the "Fafo iOS"
    // Firebase app registered for the production bundle id.
    appId: '1:149624228243:ios:ea4f666dede593f548c066',
    messagingSenderId: '149624228243',
    projectId: 'fafu-869a8',
    storageBucket: 'fafu-869a8.firebasestorage.app',
    iosBundleId: 'com.getfafo.app',
  );
}
